name: CI

on:
  push:
    branches:
      - main
      - master
      - renovate/*
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron:  '0 4 * * 5' # Fridays at 4am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.12
          - ember-lts-5.12
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-power-select-v6
          - ember-power-select-v7
          # - embroider-safe
          # - embroider-optimized

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}

  blueprint:
    name: "Blueprint"
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm test:blueprint
